package com.pocket_plan.j7_003.ui

import androidx.compose.ui.graphics.Color

val theme_light_background = Color(0xFFFFFFFF)
val theme_light_background_elevated = Color(0xFFFFFFFF)
val theme_light_on_background = Color(0xFF1B1B1B)
val theme_light_on_background_task = Color(0xffffffff)

val theme_light_hint = Color(0xFF888888)

val theme_light_birthday_today = Color(0xFFFF4757)
val theme_light_birthday_soon = Color(0xFFFF6600)

val theme_light_primary = Color(0xFFFFFFFF)
val theme_light_primary_light = Color(0xFFFFFFFF)
val theme_light_primary_dark = Color(0xFFC19797)

val theme_light_gray = Color(0xFFA5A1A1)
val theme_light_gray_l = Color(0xFFA5A1A1)
val theme_light_gray_d = Color(0xFFD3D3D3)

val theme_light_accent = Color(0xFF4FC3F7)
val theme_light_accent_clone = Color(0xFF4FC3F7)
val theme_light_button_cancel = Color(0xFFEC4B5E)
val theme_light_checked_category_title = Color(0xFFFFFFFF)
val theme_light_checked_task = Color(0xFFBDBCBC)
val theme_light_hyper_link = Color(0xFF23A8E4)
val theme_light_icon_tint = Color(0xFF4F4F4F)

val theme_light_priority_1 = Color(0xFFEC7380)
val theme_light_priority_2 = Color(0xFFFABB5D)
val theme_light_priority_3 = Color(0xFF85CF8A)

val theme_light_priority_1_darker = Color(0xFFE62929)
val theme_light_priority_2_darker = Color(0xFFE89E2E)
val theme_light_priority_3_darker = Color(0xFF39BF33)

val theme_light_priority_1_border = Color(0xFFE62929)
val theme_light_priority_2_border = Color(0xFFE89E2E)
val theme_light_priority_3_border = Color(0xFF39BF33)

val theme_light_priority_button_background_1 = Color(0xFFE62929)
val theme_light_priority_button_background_2 = Color(0xFFE89E2E)
val theme_light_priority_button_background_3 = Color(0xFF39BF33)

val theme_light_priority_button_text_1 = Color(0xFF121212)
val theme_light_priority_button_text_2 = Color(0xFF121212)
val theme_light_priority_button_text_3 = Color(0xFF121212)

val theme_light_round_accent_border = Color(0xFF0652A5)
val theme_light_round_accent_background = Color(0xFF0652A5)

val theme_light_round_red_border = Color(0xFFA80F0F)
val theme_light_round_red_background = Color(0xFFA80F0F)

val theme_light_note_red = Color(0xFFF06273)
val theme_light_note_red_darker = Color(0xffffffff)
val theme_light_note_orange = Color(0xFFF49663)
val theme_light_note_orange_darker = Color(0xffffffff)
val theme_light_note_yellow = Color(0xFFFFB649)
val theme_light_note_yellow_darker = Color(0xffffffff)
val theme_light_note_lime = Color(0xFFBACF5A)
val theme_light_note_lime_darker = Color(0xffffffff)
val theme_light_note_green = Color(0xFF8CBD77)
val theme_light_note_green_darker = Color(0xffffffff)
val theme_light_note_turquoise = Color(0xFF77BDA7)
val theme_light_note_turquoise_darker = Color(0xffffffff)
val theme_light_note_blue = Color(0xFF49B3E3)
val theme_light_note_blue_darker = Color(0xffffffff)
val theme_light_note_dark_blue = Color(0xFF4975E3)
val theme_light_note_dark_blue_darker = Color(0xffffffff)
val theme_light_note_purple = Color(0xFFCA61BB)
val theme_light_note_purple_darker = Color(0xffffffff)
val theme_light_note_dark_purple = Color(0xFF9352CD)
val theme_light_note_dark_purple_darker = Color(0xffffffff)

val theme_light_background_list_element = Color(0xFFE1E1E1)
val theme_light_go_to_sleep = Color(0xFFFF4A4A)

val theme_light_sun = Color(0xFFF3A318)

val theme_light_birthday_notify = Color(0xFF5FCFFB)
val theme_light_birthday_notify_disabled = Color(0xFFCDCDCD)
val theme_light_home_panel = Color(0xFFFFFFFF)

val theme_light_category = Color(0xFFFFFFFF)

val theme_light_month_1 = Color(0xFF3590D8)
val theme_light_month_2 = Color(0xFF48CFE1)
val theme_light_month_3 = Color(0xFF3EBA8F)
val theme_light_month_4 = Color(0xFF81C784)
val theme_light_month_5 = Color(0xFFB7DF7E)
val theme_light_month_6 = Color(0xFFEAC717)
val theme_light_month_7 = Color(0xFFFF8A65)
val theme_light_month_8 = Color(0xFFF06292)
val theme_light_month_9 = Color(0xFFBA68C8)
val theme_light_month_10 = Color(0xFF9D7DD6)
val theme_light_month_11 = Color(0xFF7986CB)
val theme_light_month_12 = Color(0xFF5966AE)

val theme_light_icon_appearance = Color(0xffffffff)
val theme_light_icon_notes = Color(0xffffffff)
val theme_light_icon_shopping = Color(0xffffffff)
val theme_light_icon_backup = Color(0xffffffff)
val theme_light_icon_about = Color(0xffffffff)

val theme_light_sonstiges = Color(0xFF455C83)
val theme_light_sonstiges_l = Color(0xFF627393)
val theme_light_obst_und_gemuese = Color(0xC42E9E15)
val theme_light_obst_und_gemuese_l = Color(0xFF80C857)
val theme_light_getraenke = Color(0xD51E429E)
val theme_light_getraenke_l = Color(0xFF5076DC)
val theme_light_nudel_und_getreide = Color(0xCECA9B0E)
val theme_light_nudel_und_getreide_l = Color(0xFFE4B641)
val theme_light_backwaren = Color(0xBA5C3804)
val theme_light_backwaren_l = Color(0xFFA17D4A)
val theme_light_kuehlregal_milch = Color(0xC1A8A5A5)
val theme_light_kuehlregal_milch_l = Color(0xFFCFCFCF)
val theme_light_kuehlregal_fleisch = Color(0xFF9A2020)
val theme_light_kuehlregal_fleisch_l = Color(0xFFC84F4F)
val theme_light_vegan = Color(0xFF98C511)
val theme_light_vegan_l = Color(0xFFA6CF26)
val theme_light_tiefkuehl = Color(0xE979A3EA)
val theme_light_tiefkuehl_l = Color(0xFF8EC2F1)
val theme_light_konserven_fertiges = Color(0xCD333333)
val theme_light_konserven_fertiges_l = Color(0xFF616161)
val theme_light_fruehstueck = Color(0xC8C35704)
val theme_light_fruehstueck_l = Color(0xFFC35704)
val theme_light_gewuerze = Color(0xD5981201)
val theme_light_gewuerze_l = Color(0xFFD5663A)
val theme_light_haushalt = Color(0xC8216150)
val theme_light_haushalt_l = Color(0xFF339E81)
val theme_light_snacks = Color(0xFFAC02AC)
val theme_light_snacks_l = Color(0xFFDC64DC)
val theme_light_backzutaten = Color(0xBA803809)
val theme_light_backzutaten_l = Color(0xFFBC7744)
val theme_light_drogerie_kosmetik = Color(0xCB32B89E)
val theme_light_drogerie_kosmetik_l = Color(0xFF7ADCC7)
val theme_light_alkohol_tabak = Color(0xBE2F0D8C)
val theme_light_alkohol_tabak_l = Color(0xFF7449DA)